version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: template_mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=template_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456